name: Test

on:
  issue_comment:
    types: [created, edited]


jobs:
  test:

    name: PR comment
    if: "${{ github.event.issue.pull_request }} && contains(github.event.comment.body, 'Please run action')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      - run: echo "${{ github.event.comment.body }}"
