name: Test

on:
  issue_comment:
    types: [created, edited]


jobs:
  test:

    name: PR comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'Please run action') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:

      - run: echo "${{ github.event.comment.body }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          touch test_file.txt
          git add test_file.txt

          git commit -m "Try to commit file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
